language: node_js
# nodejs版本
node_js: 
    - '8.11.3'

install:
  - npm install
script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git remote add origin ${TARGET}
  - git pull origin master
  - git add .
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git commit -m "update"
  - git push -f origin master

branches:
  only:
    - master