language: node_js
node_js: 
    - '8.11.3'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config --global user.name "${USER_NAME}"
  - git config --global user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${token}@${TARGET}" master:${P_BRANCH}
branches:
  only:
    - master